trigger: none

pr: none

variables:
  - group: mobile-variable-group

pool: 
  name: Reserva_Pool_Mac
  demands:
  - agent.name -equals mac_agent_m1

steps:
- checkout: self
  persistCredentials: true
  clean: true

- task: DownloadSecureFile@1
  name: apiKeyFile
  inputs:
    secureFile: 'fastlane_DD8P34TT2Q.json'

- script: |
    fastlane ios beta api_key_path:$(apiKeyPath)
  displayName: 'Deploy to TestFlight'
  workingDirectory: ios

# Etapas para Android
#- script: |
#    echo "Y" | sudo sdkmanager --install "build-tools;29.0.2" "platforms;android-29"
#  displayName: 'Install Android SDK Build Tools'

#- script: |
#    fastlane android beta
#  displayName: 'Deploy to Play Store Beta'
#  env:
#    PLAY_STORE_JSON_KEY: $(playStoreJsonKey)
#  workingDirectory: android
