  Object.defineProperty(exports, "__esModule", {
    value: true
  });
  exports.FONTS = undefined;
  var FONTS = exports.FONTS = {
    WORK_SANS_BOLD: 'WorkSans-Bold',
    WORK_SANS_BOLD_ITALIC: 'WorkSans-BoldItalic',
    WORK_SANS_ITALIC: 'WorkSans-Italic',
    WORK_SANS_LIGHT: 'WorkSans-Light',
    WORK_SANS_LIGHT_ITALIC: 'WorkSans-LightItalic',
    WORK_SANS_REGULAR: 'WorkSans-Regular',
    RESERVA_SANS_BLACK: 'ReservaSans-Black',
    RESERVA_SANS_BLACK_ITALIC: 'ReservaSans-BlackItalic',
    RESERVA_SANS_BOLD: 'ReservaSans-Bold',
    RESERVA_SANS_BOLD_ITALIC: 'ReservaSans-BoldItalic',
    RESERVA_SANS_ITALIC: 'ReservaSans-Italic',
    RESERVA_SANS_LIGHT: 'ReservaSans-Light',
    RESERVA_SANS_LIGHT_ITALIC: 'ReservaSans-LightItalic',
    RESERVA_SANS_MEDIUM: 'ReservaSans-Medium',
    RESERVA_SANS_MEDIUM_ITALIC: 'ReservaSans-MediumItalic',
    RESERVA_SANS_REGULAR: 'ReservaSans-Regular',
    RESERVA_SANS_THIN: 'ReservaSans-Thin',
    RESERVA_SANS_THIN_ITALIC: 'ReservaSans-ThinItalic',
    RESERVA_SERIF_BLACK: 'ReservaSerif-Black',
    RESERVA_SERIF_BLACK_ITALIC: 'ReservaSerif-BlackItalic',
    RESERVA_SERIF_BOLD: 'ReservaSerif-Bold',
    RESERVA_SERIF_BOLD_ITALIC: 'ReservaSerif-BoldItalic',
    RESERVA_SERIF_ITALIC: 'ReservaSerif-Italic',
    RESERVA_SERIF_LIGHT: 'ReservaSerif-Light',
    RESERVA_SERIF_LIGHT_ITALIC: 'ReservaSerif-LightItalic',
    RESERVA_SERIF_MEDIUM: 'ReservaSerif-Medium',
    RESERVA_SERIF_MEDIUM_ITALIC: 'ReservaSerif-MediumItalic',
    RESERVA_SERIF_REGULAR: 'ReservaSerif-Regular',
    RESERVA_SERIF_THIN: 'ReservaSerif-Thin',
    RESERVA_SERIF_THIN_ITALIC: 'ReservaSerif-ThinItalic',
    NUNITO_BLACK: 'Nunito-Black',
    NUNITO_BLACK_ITALIC: 'Nunito-BlackItalic',
    NUNITO_BOLD: 'Nunito-Bold',
    NUNITO_BOLD_ITALIC: 'Nunito-BoldItalic',
    NUNITO_EXTRA_BOLD: 'Nunito-ExtraBold',
    NUNITO_EXTRA_BOLD_ITALIC: 'Nunito-ExtraBoldItalic',
    NUNITO_EXTRA_LIGHT: 'Nunito-ExtraLight',
    NUNITO_EXTRA_LIGHT_ITALIC: 'Nunito-ExtraLightItalic',
    NUNITO_ITALIC: 'Nunito-Italic',
    NUNITO_LIGHT: 'Nunito-Light',
    NUNITO_LIGHT_ITALIC: 'Nunito-LightItalic',
    NUNITO_REGULAR: 'Nunito-Regular',
    NUNITO_SEMI_BOLD: 'Nunito-SemiBold',
    NUNITO_SEMI_BOLD_ITALIC: 'Nunito-SemiBoldItalic',
    RESERVA_DISPLAY_REGULAR: 'ReservaDisplay-Regular',
    ARIAL: 'Arial',
    ARIAL_BOLD: 'Arial-Bold',
    ARIAL_BOLD_ITALIC: 'Arial-Bold-Italic',
    ARIAL_ITALIC: 'Arial-Italic'
  };
