  Object.defineProperty(exports, "__esModule", {
    value: true
  });
  exports.svgs = exports.default = exports.commons = undefined;
  /* eslint-disable global-require */
  /* mapping of images used as icons */
  var commons = exports.commons = {
    foraDoAr: _$$_REQUIRE(_dependencyMap[0]),
    topBannerMock1: _$$_REQUIRE(_dependencyMap[1]),
    homeMock1: _$$_REQUIRE(_dependencyMap[2]),
    homeMock2: _$$_REQUIRE(_dependencyMap[3]),
    homeMock3: _$$_REQUIRE(_dependencyMap[4]),
    homeMock4: _$$_REQUIRE(_dependencyMap[5]),
    bannerOffer: _$$_REQUIRE(_dependencyMap[6]),
    bannerCatalog: _$$_REQUIRE(_dependencyMap[7]),
    shirt1: _$$_REQUIRE(_dependencyMap[8]),
    shirt2: _$$_REQUIRE(_dependencyMap[9]),
    shirt3: _$$_REQUIRE(_dependencyMap[10]),
    shirt4: _$$_REQUIRE(_dependencyMap[11]),
    visa: _$$_REQUIRE(_dependencyMap[12]),
    mastercard: _$$_REQUIRE(_dependencyMap[13]),
    cardImage: _$$_REQUIRE(_dependencyMap[14]),
    americanExpress: _$$_REQUIRE(_dependencyMap[15]),
    umPCincoPLogo: _$$_REQUIRE(_dependencyMap[16]),
    elo: _$$_REQUIRE(_dependencyMap[17]),
    cupomModalBackground: _$$_REQUIRE(_dependencyMap[18]),
    bagEmpty: _$$_REQUIRE(_dependencyMap[19]),
    imageCashback: _$$_REQUIRE(_dependencyMap[20]),
    cardFront: _$$_REQUIRE(_dependencyMap[21]),
    cardVerso: _$$_REQUIRE(_dependencyMap[22]),
    clothingCare1: _$$_REQUIRE(_dependencyMap[23]),
    clothingCareWash: _$$_REQUIRE(_dependencyMap[24]),
    clothingCareBleach: _$$_REQUIRE(_dependencyMap[25]),
    clothingCareDrying: _$$_REQUIRE(_dependencyMap[26]),
    clothingCarePass: _$$_REQUIRE(_dependencyMap[27]),
    clothingCareProfessionalWashing: _$$_REQUIRE(_dependencyMap[28]),
    localReserva: _$$_REQUIRE(_dependencyMap[29]),
    pinYou: _$$_REQUIRE(_dependencyMap[30]),
    bannerLogin: _$$_REQUIRE(_dependencyMap[31]),
    headerLogin: _$$_REQUIRE(_dependencyMap[32]),
    purchaseConfirmation: _$$_REQUIRE(_dependencyMap[33]),
    withoutInternet: _$$_REQUIRE(_dependencyMap[34]),
    update: _$$_REQUIRE(_dependencyMap[35]),
    searchNotFound: _$$_REQUIRE(_dependencyMap[36]),
    saleOff: _$$_REQUIRE(_dependencyMap[37]),
    logoQRCode: _$$_REQUIRE(_dependencyMap[38]),
    imageNotFound: _$$_REQUIRE(_dependencyMap[39]),
    noStoresFound: _$$_REQUIRE(_dependencyMap[40]),
    QrcodeBackground: _$$_REQUIRE(_dependencyMap[41]),
    whatsapp: _$$_REQUIRE(_dependencyMap[42]),
    twitter: _$$_REQUIRE(_dependencyMap[43]),
    instagram: _$$_REQUIRE(_dependencyMap[44]),
    facebook: _$$_REQUIRE(_dependencyMap[45]),
    raceImageBackground: _$$_REQUIRE(_dependencyMap[46]),
    dividerReserva: _$$_REQUIRE(_dependencyMap[47]),
    GuideShort: _$$_REQUIRE(_dependencyMap[48]),
    GuideSungaCueca: _$$_REQUIRE(_dependencyMap[49]),
    GuideSueter: _$$_REQUIRE(_dependencyMap[50]),
    GuideJaqueta: _$$_REQUIRE(_dependencyMap[51]),
    GuideHoodie: _$$_REQUIRE(_dependencyMap[52]),
    GuideCalca: _$$_REQUIRE(_dependencyMap[53]),
    GuideMangaCurta: _$$_REQUIRE(_dependencyMap[54]),
    GuideMangaLonga: _$$_REQUIRE(_dependencyMap[55]),
    GuideCamiseta: _$$_REQUIRE(_dependencyMap[56]),
    GuideBermuda: _$$_REQUIRE(_dependencyMap[57]),
    GuidePolo: _$$_REQUIRE(_dependencyMap[58]),
    noWishList: _$$_REQUIRE(_dependencyMap[59]),
    zoomHand: _$$_REQUIRE(_dependencyMap[60]),
    arrowInstruction: _$$_REQUIRE(_dependencyMap[61]),
    selectRectangle: _$$_REQUIRE(_dependencyMap[62]),
    emptyProductCatalog: _$$_REQUIRE(_dependencyMap[63]),
    search: _$$_REQUIRE(_dependencyMap[64]),
    filledHeart: _$$_REQUIRE(_dependencyMap[65]),
    unfilledHeart: _$$_REQUIRE(_dependencyMap[66]),
    share: _$$_REQUIRE(_dependencyMap[67]),
    expand: _$$_REQUIRE(_dependencyMap[68]),
    arrowRight: _$$_REQUIRE(_dependencyMap[69]),
    uncheckedBox: _$$_REQUIRE(_dependencyMap[70]),
    checkedBox: _$$_REQUIRE(_dependencyMap[71]),
    help: _$$_REQUIRE(_dependencyMap[72]),
    discountFlag: _$$_REQUIRE(_dependencyMap[73]),
    close: _$$_REQUIRE(_dependencyMap[74]),
    copy: _$$_REQUIRE(_dependencyMap[75]),
    faq: _$$_REQUIRE(_dependencyMap[76]),
    chat: _$$_REQUIRE(_dependencyMap[77]),
    pinPlace: _$$_REQUIRE(_dependencyMap[78]),
    heart: _$$_REQUIRE(_dependencyMap[79]),
    document: _$$_REQUIRE(_dependencyMap[80]),
    profile: _$$_REQUIRE(_dependencyMap[81]),
    roulet: _$$_REQUIRE(_dependencyMap[82]),
    shipping1: _$$_REQUIRE(_dependencyMap[83]),
    shipping2: _$$_REQUIRE(_dependencyMap[84]),
    signup1: _$$_REQUIRE(_dependencyMap[85]),
    signup2: _$$_REQUIRE(_dependencyMap[86]),
    signup3: _$$_REQUIRE(_dependencyMap[87]),
    signup4: _$$_REQUIRE(_dependencyMap[88]),
    signup5: _$$_REQUIRE(_dependencyMap[89]),
    ios14: _$$_REQUIRE(_dependencyMap[90]),
    reservaIcon: _$$_REQUIRE(_dependencyMap[91]),
    greenCheck: _$$_REQUIRE(_dependencyMap[92]),
    config: _$$_REQUIRE(_dependencyMap[93]),
    cutlery: _$$_REQUIRE(_dependencyMap[94]),
    green1p5p: _$$_REQUIRE(_dependencyMap[95]),
    black1p5p: _$$_REQUIRE(_dependencyMap[96]),
    chevronLeftFill: _$$_REQUIRE(_dependencyMap[97]),
    chevronRightFill: _$$_REQUIRE(_dependencyMap[98]),
    addition: _$$_REQUIRE(_dependencyMap[99]),
    subtraction: _$$_REQUIRE(_dependencyMap[100]),
    abandonedCartBag: _$$_REQUIRE(_dependencyMap[101]),
    newsletter: _$$_REQUIRE(_dependencyMap[102]),
    logo: _$$_REQUIRE(_dependencyMap[103])
  };

  /* mapping of svgs used as icons */
  var svgs = exports.svgs = {
    logoPrime: _$$_REQUIRE(_dependencyMap[104]).default,
    chevronRight: _$$_REQUIRE(_dependencyMap[105]).default,
    info: _$$_REQUIRE(_dependencyMap[106]).default,
    infoSuccess: _$$_REQUIRE(_dependencyMap[107]).default,
    closeIcon: _$$_REQUIRE(_dependencyMap[108]).default,
    trash: _$$_REQUIRE(_dependencyMap[109]).default,
    hanger: _$$_REQUIRE(_dependencyMap[110]).default,
    sizeGuideIcon: _$$_REQUIRE(_dependencyMap[111]).default,
    checkedRounded: _$$_REQUIRE(_dependencyMap[112]).default,
    arrowBack: _$$_REQUIRE(_dependencyMap[113]).default,
    personalize: _$$_REQUIRE(_dependencyMap[114]).default
  };
  var _default = exports.default = Object.assign({}, commons, svgs);
