/* eslint-disable global-require */
/* mapping of images used as icons */
export const commons = {
  foraDoAr: require('../../../assets/common/fora-do-ar.png'),
  topBannerMock1: require('../../../assets/common/topBannerMock1.png'),
  homeMock1: require('../../../assets/common/homeMock1.png'),
  homeMock2: require('../../../assets/common/homeMock2.png'),
  homeMock3: require('../../../assets/common/homeMock3.png'),
  homeMock4: require('../../../assets/common/homeMock4.png'),
  bannerOffer: require('../../../assets/common/bannerOffer.png'),
  bannerCatalog: require('../../../assets/common/bannerCatalog.png'),
  shirt1: require('../../../assets/common/shirt1.png'),
  shirt2: require('../../../assets/common/shirt2.png'),
  shirt3: require('../../../assets/common/shirt3.png'),
  shirt4: require('../../../assets/common/shirt4.png'),
  visa: require('../../../assets/common/visa.png'),
  mastercard: require('../../../assets/common/mastercard.png'),
  americanExpress: require('../../../assets/common/americanExpress.png'),
  elo: require('../../../assets/common/elo.png'),
  cupomModalBackground: require('../../../assets/common/cupomModalBackground.png'),
  bagEmpty: require('../../../assets/common/bagEmpty.png'),
  imageCashback: require('../../../assets/common/image_cashback.png'),
  cardFront: require('../../../assets/common/cardFront.png'),
  cardVerso: require('../../../assets/common/cardVerso.png'),
  clothingCare1: require('../../../assets/common/clothing-care1.png'),
  clothingCareWash: require('../../../assets/common/clothingCareWash.png'),
  clothingCareBleach: require('../../../assets/common/clothingCareBleach.png'),
  clothingCareDrying: require('../../../assets/common/clothingCareDrying.png'),
  clothingCarePass: require('../../../assets/common/clothingCarePass.png'),
  clothingCareProfessionalWashing: require('../../../assets/common/clothingCareProfessionalWashing.png'),
  localReserva: require('../../../assets/common/local-reserva.png'),
  pinYou: require('../../../assets/common/pinYou.png'),
  bannerLogin: require('../../../assets/common/banner-login.png'),
  headerLogin: require('../../../assets/common/headerLogin.png'),
  purchaseConfirmation: require('../../../assets/common/purchaseConfirmation.png'),
  withoutInternet: require('../../../assets/common/withoutInternet.png'),
  update: require('../../../assets/common/update.png'),
  searchNotFound: require('../../../assets/common/searchNotFound.png'),
  saleOff: require('../../../assets/common/saleOff.png'),
  logoQRCode: require('../../../assets/common/logoQRCode.png'),
  imageNotFound: require('../../../assets/common/imageNotFound.png'),
  noStoresFound: require('../../../assets/common/noStoresFound.png'),
  QrcodeBackground: require('../../../assets/common/QrcodeBackground.png'),
  whatsapp: require('../../../assets/common/whatsapp.png'),
  twitter: require('../../../assets/common/twitter.png'),
  instagram: require('../../../assets/common/instagram.png'),
  facebook: require('../../../assets/common/facebook.png'),
  raceImageBackground: require('../../../assets/common/raceImageBackground.png'),
  dividerReserva: require('../../../assets/common/dividerReserva.png'),
  GuideShort: require('../../../assets/common/Short.png'),
  GuideSungaCueca: require('../../../assets/common/SungaCueca.png'),
  GuideSueter: require('../../../assets/common/Sueter.png'),
  GuideJaqueta: require('../../../assets/common/Jaqueta.png'),
  GuideHoodie: require('../../../assets/common/Hoodie.png'),
  GuideCalca: require('../../../assets/common/Calca.png'),
  GuideMangaCurta: require('../../../assets/common/CamisaMangaCurta.png'),
  GuideMangaLonga: require('../../../assets/common/CamisaMangaLonga.png'),
  GuideCamiseta: require('../../../assets/common/Camiseta.png'),
  GuideBermuda: require('../../../assets/common/Bermuda.png'),
  GuidePolo: require('../../../assets/common/Polo.png'),
  noWishList: require('../../../assets/common/noWishList.png'),
  zoomHand: require('../../../assets/common/zoomHand.png'),
  arrowInstruction: require('../../../assets/common/arrowInstruction.png'),
  selectRectangle: require('../../../assets/common/selectRectangle.png'),
  emptyProductCatalog: require('../../../assets/common/emptyProductCatalog.png'),
  search: require('../../../assets/common/search.png'),
  discountFlag: require('../../../assets/common/discountFlag.png'),
  close: require('../../../assets/common/close.png'),
  copy: require('../../../assets/common/copy.png'),
  faq: require('../../../assets/common/faq.png'),
  chat: require('../../../assets/common/chat.png'),
  pinPlace: require('../../../assets/common/pinPlace.png'),
  heart: require('../../../assets/common/heart.png'),
  document: require('../../../assets/common/document.png'),
  profile: require('../../../assets/common/profile.png'),
  roulet: require('../../../assets/common/roulet.png'),
};

/* mapping of svgs used as icons */
export const svgs = {
  logoPrime: require('../svgs/LogoPrime').default,
  chevronRight: require('../svgs/ChevronRight').default,
};

type TIconsKeys = keyof typeof commons;
type TSVGsKeys = keyof typeof svgs;

export type TIcons = TIconsKeys | TSVGsKeys;

export default {
  ...commons,
  ...svgs,
};
