# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"

  lane :beta do

  cocoapods(
    podfile: "reserva",
    use_bundle_exec: false
  )

  app_store_connect_api_key(
    key_id: "DD8P34TT2Q",
    issuer_id: "1694feb0-01bc-43e2-ae9a-51e7b25e810c",
    key_filepath: "fastlane/AuthKey_DD8P34TT2Q.p8",
    duration: 1200, # optional (maximum 1200)
    in_house: false # optional but may be required if using match/sigh
  )

  enable_automatic_code_signing(
    path: "reserva.xcodeproj"
    )

  produce(
    app_identifier: "com.globalsys.reserva.OneSignalNotificationServiceExtension",
    app_name: "OneSignalNotificationServiceExtension",
    skip_itc: true,
    enable_services: {
      "associated_domains": "on",
      "app_group": "on",
      "app_attest": "on",
      "push_notification": "on",
    }
  )

  gym(
    scheme: "reserva",
    workspace: "reserva.xcworkspace",
    export_method: "app-store",
    configuration: "Release",
    clean: true,
    output_directory: "build"
  )

  testflight(
    ipa: "build/reserva.ipa", 
    skip_waiting_for_build_processing: true
  )

  end
end
