# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"

  lane :beta do

  increment_build_number(xcodeproj: "reserva.xcodeproj")
  increment_version_number(version_number: "999999")

#  cocoapods(
#    podfile: "reserva",
#    use_bundle_exec: false
#  )

  app_store_connect_api_key(
    key_id: "DD8P34TT2Q",
    issuer_id: "1694feb0-01bc-43e2-ae9a-51e7b25e810c",
    key_filepath: "fastlane/AuthKey_DD8P34TT2Q.p8",
    duration: 1200, # optional (maximum 1200)
    in_house: false # optional but may be required if using match/sigh
  )
 
  gym(
    scheme: "reserva",
    xcargs: "-jobs 4",
    workspace: "reserva.xcworkspace",
    export_method: "app-store",
    configuration: "Release",
    output_directory: "build",
    include_bitcode: false,
    include_symbols: false,
    skip_profile_detection: true,
    silent: false,
    clean: false,
    codesigning_identity: "iPhone Distribution: Tiferet Comercio de Roupas LTDA (N3UDSXJ25B)",
    export_options: {
      method: "app-store",
      provisioningProfiles: {
        "com.globalsys.reserva" => "match.com.globalsys.reserva",
        "com.globalsys.reserva.OneSignalNotificationServiceExtension" => "match.com.globalsys.reserva.oneSignal"
      }
    }
  )

  pilot(
      api_key_path: "fastlane/fastlane_DD8P34TT2Q.json",
      ipa: "build/reserva.ipa",
      skip_waiting_for_build_processing: true	 
  )

  end
end
