export const mockPurchaseData = [
  {
    sellers: [
      {
        id: '1',
        name: 'applojausereservaqa',
        logo: '',
      },
    ],
    orderId: '1356074561143-01',
    orderGroup: '1356074561143',
    state: 'invoiced',
    isCheckedIn: false,
    sellerOrderId: '00-1356074561143-01',
    storeId: null,
    checkedInPickupPointId: null,
    value: 8900,
    items: [
      {
        uniqueId: '3F784CB89A9E4C69B42414FB8D859759',
        id: '355174',
        productId: '35462',
        productRefId: '0062577',
        refId: '006257731203',
        ean: '0062577312',
        name: 'CAMISETA ESTAMPADA CYBER MARINHO - G',
        skuName: 'MARINHO - G',
        modalType: null,
        parentItemIndex: null,
        parentAssemblyBinding: null,
        assemblies: [],
        priceValidUntil: '2024-08-22T15:13:50Z',
        tax: 0,
        price: 14900,
        listPrice: 24900,
        manualPrice: null,
        manualPriceAppliedBy: null,
        sellingPrice: 8900,
        rewardValue: 0,
        isGift: false,
        additionalInfo: {
          dimension: {
            cubicweight: 0,
            height: 20,
            length: 20,
            weight: 250,
            width: 20,
          },
          brandName: 'RESERVA',
          brandId: '1',
          offeringInfo: null,
          offeringType: null,
          offeringTypeId: null,
          categoriesIds: '/1/259/260/262/',
          productClusterId: '327,506,560,935,939,940,941,945,955,1003,1004,1046,1154,1198,1199,1266,1277,1310,1311,1312,1335,1338,1372,1373,1375,1397,1405,1410,1439,1627,1628,1697,1721,1724,1732,1742,1745,1746,1748,1749,1752,1777,1807,1809,1950,1963,2075,2081,2100,2141,2164,2227,2239,2247,2248,2269,2287,2291,2305,2334,2360,2362,2363,2367,2372,2392,2393,2406,2407,2418,2478,2491,2505,2508,2524,2540,2542,2547,2580,2630,2639,2650,2733,2772,2782,2807',
          commercialConditionId: '1',
        },
        preSaleDate: null,
        productCategoryIds: '/1/259/260/262/',
        productCategories: {
          1: 'Reserva',
          259: 'Bazar',
          260: 'Masculino',
          262: 'Camisetas',
        },
        quantity: 1,
        seller: '1',
        sellerChain: [
          '1',
        ],
        imageUrl: 'http://lojausereserva.vteximg.com.br/arquivos/ids/6684702-55-55/0062577312_01.jpg?v=637828641798830000',
        detailUrl: '/camiseta-estampada-cyber0062577/p',
        components: [],
        bundleItems: [],
        attachments: [],
        attachmentOfferings: [],
        offerings: [
          {
            type: 'Embalagem pra Presente',
            typeId: '1',
            id: '352024',
            name: 'Embalagem pra Presente',
            allowGiftMessage: true,
            attachmentOfferings: [
              {
                name: 'message',
                required: false,
                schema: {
                  text: {
                    maximumNumberOfCharacters: 300,
                    domain: [],
                  },
                },
              },
            ],
            price: 0,
          },
        ],
        priceTags: [
          {
            name: 'discount@price-5293ff82-d8fb-49ff-901c-76c39824eca6#27dc4257-f7ff-4844-9871-219a867cad7d',
            value: -2500,
            rawValue: -25,
            isPercentual: false,
            identifier: '5293ff82-d8fb-49ff-901c-76c39824eca6',
            owner: 'applojausereservaqa',
          },
          {
            name: 'discount@price-aef5199d-57a7-402f-b0e6-f88b6b3051fb#bb47e433-beec-46ff-9fc5-753f2a42754a',
            value: -3500,
            rawValue: -35,
            isPercentual: false,
            identifier: 'aef5199d-57a7-402f-b0e6-f88b6b3051fb',
            owner: 'applojausereservaqa',
          },
        ],
        availability: 'available',
        measurementUnit: 'un',
        unitMultiplier: 1,
        manufacturerCode: null,
        priceDefinition: {
          calculatedSellingPrice: 8900,
          total: 8900,
          sellingPrices: [
            {
              value: 8900,
              quantity: 1,
            },
          ],
        },
      },
    ],
    totals: [
      {
        id: 'Items',
        name: 'Total dos Itens',
        value: 14900,
      },
      {
        id: 'Discounts',
        name: 'Total dos Descontos',
        value: -6000,
      },
      {
        id: 'Shipping',
        name: 'Total do Frete',
        value: 0,
      },
      {
        id: 'Tax',
        name: 'Total da Taxa',
        value: 0,
      },
    ],
    clientProfileData: {
      email: 'nogueirahy@gmail.com',
      firstName: 'Leonardo',
      lastName: 'Henrique Nogueira',
      document: '02190339197',
      documentType: 'cpf',
      phone: '+5567992146730',
      corporateName: null,
      tradeName: null,
      corporateDocument: null,
      stateInscription: null,
      corporatePhone: null,
      isCorporate: false,
      profileCompleteOnLoading: true,
      profileErrorOnLoading: false,
      customerClass: null,
      userProfileId: '4d35c3cf-d4a1-4c52-a421-66d8f97f1b10',
      isProspect: false,
    },
    ratesAndBenefitsData: {
      rateAndBenefitsIdentifiers: [
        {
          id: '5293ff82-d8fb-49ff-901c-76c39824eca6',
          name: 'Reserva | Exclusivo Ofertas',
          featured: false,
          description: 'Reserva | BAZAR - De 149 Por 124',
          matchedParameters: {
            'Seller@CatalogSystem': 'lojausereservaondemand,1,lojausereservago|inclusive',
            'progressiveDiscount@Marketing': '355174',
          },
          additionalInfo: null,
        },
        {
          id: 'aef5199d-57a7-402f-b0e6-f88b6b3051fb',
          name: 'CRM Madruga Camisetas',
          featured: false,
          description: 'Camisetas por R$89',
          matchedParameters: {
            'Seller@CatalogSystem': 'lojausereservaondemand,1,lojausereservago|inclusive',
            'productCluster@CatalogSystem': '2393|inclusive',
          },
          additionalInfo: null,
        },
      ],
    },
    shippingData: {
      address: {
        addressType: 'pickup',
        receiverName: 'Leonardo Henrique Nogueira',
        addressId: '734123',
        isDisposable: true,
        postalCode: '57038-000',
        city: 'Maceió',
        state: 'AL',
        country: 'BRA',
        street: 'Avenida Comendador Gustavo Paiva',
        number: '5945',
        neighborhood: 'Cruz das Almas',
        complement: 'SALA 2013/2014',
        reference: null,
        geoCoordinates: [
          -35.69907,
          -9.627273,
        ],
      },
      logisticsInfo: [
        {
          itemIndex: 0,
          selectedSla: 'Retire em Loja (734123)',
          selectedDeliveryChannel: 'pickup-in-point',
          addressId: '734123',
          slas: [
            {
              id: 'Padrão',
              deliveryChannel: 'delivery',
              name: 'Padrão',
              deliveryIds: [
                {
                  courierId: '4186',
                  warehouseId: '1ad55d0',
                  dockId: '18a7212',
                  courierName: 'RARO LOG',
                  quantity: 1,
                  kitItemDetails: [],
                  accountCarrierName: null,
                },
              ],
              shippingEstimate: '3bd',
              shippingEstimateDate: null,
              lockTTL: '10d',
              availableDeliveryWindows: [],
              deliveryWindow: null,
              price: 2790,
              listPrice: 2790,
              tax: 0,
              pickupStoreInfo: {
                isPickupStore: false,
                friendlyName: null,
                address: null,
                additionalInfo: null,
                dockId: null,
              },
              pickupPointId: null,
              pickupDistance: 0,
              polygonName: '',
              transitTime: '2bd',
            },
            {
              id: 'Retire em Loja (734123)',
              deliveryChannel: 'pickup-in-point',
              name: 'Retire em Loja (734123)',
              deliveryIds: [
                {
                  courierId: '0',
                  warehouseId: '1ad55d0',
                  dockId: 'Pick Up',
                  courierName: 'Retirada em Loja  - Fallback',
                  quantity: 1,
                  kitItemDetails: [],
                  accountCarrierName: null,
                },
              ],
              shippingEstimate: '13bd',
              shippingEstimateDate: '2023-09-11T21:00:00Z',
              lockTTL: '10d',
              availableDeliveryWindows: [],
              deliveryWindow: null,
              price: 0,
              listPrice: 0,
              tax: 0,
              pickupStoreInfo: {
                isPickupStore: true,
                friendlyName: 'RESERVA MACEIO',
                address: {
                  addressType: 'pickup',
                  receiverName: null,
                  addressId: '734123',
                  isDisposable: true,
                  postalCode: '57038-000',
                  city: 'Maceió',
                  state: 'AL',
                  country: 'BRA',
                  street: 'Avenida Comendador Gustavo Paiva',
                  number: '5945',
                  neighborhood: 'Cruz das Almas',
                  complement: 'SALA 2013/2014',
                  reference: null,
                  geoCoordinates: [
                    -35.69907,
                    -9.627273,
                  ],
                },
                additionalInfo: 'Obrigatório apresentar documento de identificação',
                dockId: 'Pick Up',
              },
              pickupPointId: '1_734123',
              pickupDistance: 0.5716590285301208,
              polygonName: '',
              transitTime: '12bd',
            },
          ],
          shipsTo: [
            'BRA',
            'DEU',
            'SAL',
            'ARG',
            'AUS',
            'CAN',
            'CHL',
            'ECU',
            'ESP',
            'USA',
            'FRA',
            'IRL',
            'ITA',
            'MEX',
            'POL',
            'PRT',
            'GBR',
            'CHE',
            'SGP',
          ],
          itemId: '355174',
          deliveryChannels: [
            {
              id: 'delivery',
            },
            {
              id: 'pickup-in-point',
            },
          ],
          price: 0,
          listPrice: 0,
          shippingEstimate: '13bd',
          dockEstimate: '1bd',
          shippingEstimateDate: '2023-09-11T21:00:00Z',
          lockTTL: '10d',
          deliveryCompany: null,
          polygonName: '',
          transitTime: '12bd',
          sellingPrice: 0,
          deliveryIds: [
            {
              courierId: '0',
              warehouseId: '1ad55d0',
              dockId: 'Pick Up',
              courierName: 'Retirada em Loja  - Fallback',
              quantity: 1,
              kitItemDetails: null,
              accountCarrierName: 'lojausereserva',
            },
          ],
          deliveryWindow: null,
          pickupPointId: '1_734123',
          pickupStoreInfo: {
            isPickupStore: true,
            friendlyName: 'RESERVA MACEIO',
            address: {
              addressType: 'pickup',
              receiverName: null,
              addressId: '734123',
              isDisposable: true,
              postalCode: '57038-000',
              city: 'Maceió',
              state: 'AL',
              country: 'BRA',
              street: 'Avenida Comendador Gustavo Paiva',
              number: '5945',
              neighborhood: 'Cruz das Almas',
              complement: 'SALA 2013/2014',
              reference: null,
              geoCoordinates: [
                -35.69907,
                -9.627273,
              ],
            },
            additionalInfo: 'Obrigatório apresentar documento de identificação',
            dockId: 'Pick Up',
          },
          pickupDistance: 0.5716590285301208,
        },
      ],
      selectedAddresses: [
        {
          addressType: 'pickup',
          receiverName: 'Leonardo Henrique Nogueira',
          addressId: '734123',
          isDisposable: true,
          postalCode: '57038-000',
          city: 'Maceió',
          state: 'AL',
          country: 'BRA',
          street: 'Avenida Comendador Gustavo Paiva',
          number: '5945',
          neighborhood: 'Cruz das Almas',
          complement: 'SALA 2013/2014',
          reference: null,
          geoCoordinates: [
            -35.69907,
            -9.627273,
          ],
        },
      ],
      availableAddresses: [
        {
          addressType: 'pickup',
          receiverName: 'Leonardo Henrique Nogueira',
          addressId: '734123',
          isDisposable: true,
          postalCode: '57038-000',
          city: 'Maceió',
          state: 'AL',
          country: 'BRA',
          street: 'Avenida Comendador Gustavo Paiva',
          number: '5945',
          neighborhood: 'Cruz das Almas',
          complement: 'SALA 2013/2014',
          reference: null,
          geoCoordinates: [
            -35.69907,
            -9.627273,
          ],
        },
      ],
      trackingHints: [],
      pickupPoints: [
        {
          friendlyName: 'RESERVA MACEIO',
          address: {
            addressType: 'pickup',
            receiverName: null,
            addressId: '734123',
            isDisposable: true,
            postalCode: '57038-000',
            city: 'Maceió',
            state: 'AL',
            country: 'BRA',
            street: 'Avenida Comendador Gustavo Paiva',
            number: '5945',
            neighborhood: 'Cruz das Almas',
            complement: 'SALA 2013/2014',
            reference: null,
            geoCoordinates: [
              -35.69907,
              -9.627273,
            ],
          },
          additionalInfo: 'Obrigatório apresentar documento de identificação',
          id: '1_734123',
          businessHours: [
            {
              DayOfWeek: 0,
              OpeningTime: '14:00:00',
              ClosingTime: '20:00:00',
            },
            {
              DayOfWeek: 1,
              OpeningTime: '10:00:00',
              ClosingTime: '22:00:00',
            },
            {
              DayOfWeek: 2,
              OpeningTime: '10:00:00',
              ClosingTime: '22:00:00',
            },
            {
              DayOfWeek: 3,
              OpeningTime: '10:00:00',
              ClosingTime: '22:00:00',
            },
            {
              DayOfWeek: 4,
              OpeningTime: '10:00:00',
              ClosingTime: '22:00:00',
            },
            {
              DayOfWeek: 5,
              OpeningTime: '10:00:00',
              ClosingTime: '22:00:00',
            },
            {
              DayOfWeek: 6,
              OpeningTime: '10:00:00',
              ClosingTime: '22:00:00',
            },
          ],
        },
      ],
      isFOB: null,
    },
    paymentData: {
      giftCards: [],
      transactions: [
        {
          isActive: true,
          transactionId: 'EBCDC39409DB490BBC658D96C72371A9',
          merchantName: 'APPLOJAUSERESERVAQA',
          payments: [
            {
              id: '38A3120F3B06416684A25397BE2B9C5A',
              paymentSystem: '125',
              paymentSystemName: 'Pix',
              value: 8900,
              installments: 1,
              connectorResponses: {
                Tid: '1720447202',
                ReturnCode: null,
                Message: null,
                acquirer: 'pagarme',
                paymentId: '38A3120F3B06416684A25397BE2B9C5A',
                status: 'approved',
                tid: '1720447202',
                paymentAppData: '{"payload":"{\\"code\\":\\"00020101021226820014br.gov.bcb.pix2560pix.stone.com.br/pix/v2/b846f2c1-7eb3-4531-81da-19da73a4ca9e520400005303986540589.005802BR5914Conta Primaria6014RIO DE JANEIRO62290525pacllmgbiledtsq1flc9qi64c6304F5D7\\",\\"qrCodeBase64Image\\":\\"iVBORw0KGgoAAAANSUhEUgAAAPQAAAD0AQMAAACW4Zm9AAAABlBMVEUAAAD///\\\\u002Bl2Z/dAAACu0lEQVR4nO2ZUW7kQAhEuQH3vyU3YKlHtz0jrfIHH1FGE8Xu15GQgaLasfzxE/bHfzs3M4\\\\u002B0\\\\u002BrpbcJPpLK9wr6/Xdf2K1JJujOUdXnFVeAqtlkO7\\\\u002BKXlLe6hB6KQap8Xdl/lEbqqCJUe3XjuceVHV6b0OOFVuN/5G\\\\u002BSK6T\\\\u002Bfr/qd5PRhbQsnLCUrKdeP/p3kFYd1cUbXSN2rXyN2eBVCqB1VE67CpFBCNbrCU49DMVZIak51Kn9lucJrpUDnpCKqZUMd63KFJ8lBJBVbBIWpvOUKZ8slPR5Cd37im\\\\u002BanQ2kQZcspkeyNG1zyqOZQjqRP3vE\\\\u002B/TvOk/HIWG5d1P589GmYKzYpRN4q6eTk1edprm8kD8aeKklkcoVrJCsUhqKEgeFEy65wqZK3ScKZhEa06tV2OMIUrY4IU0ia3vxMc0MIzkPpeg382c3fME\\\\u002BFJo9kPZHoT3/zs8DZoZGsWR3neT39O8yphciez0jFuckdjiIrQZIFb6eCT7jPZ5gzG5DGpEhkDAynusNlRR1HYqQqMYpcrXD1oyPQR6iDr9/8jHMdCTiW9LM6kznzo38nuVMjong13Zq1T13hqsi485lncqyB7/D2Jczn3qkDopO1Fa477wLtQ4Kdv3rm4yxP3EBg0K2dEb3ie5z8oFKZdszxObHPc\\\\u002BdUascZRYfl9ujzND8WqY9FiTnmfdUzv\\\\u002Bd58GrMuyJaMr/84yznWM58RiBozIz3fDbMAyeUfSplVDs\\\\u002Bwd1XuLU3tJYlziW8L3v0e5hHC7EWmUw4E\\\\u002BbTDpcXvYe0O5/vmXWFcypTkoIdEob49GfD3LAnkofjyuiMj/4Y5v1Wts8E3pFSm2vcjhfIbtTzfs7ufN7hZz6rS3k/bO/5dYFbD2bEkuEY8c6Pac4K/x85MtFvLPMjf5PcWgzbn1Mrzs/j34b5T58//sv5P163Ld\\\\u002BOKWibAAAAAElFTkSuQmCC\\"}"}',
                delayToAutoSettle: '1',
                delayToCancel: '0',
                maxValue: '89.0',
              },
              referenceValue: 8900,
              cardHolder: null,
              cardNumber: null,
              firstDigits: null,
              lastDigits: null,
              cvv2: null,
              expireMonth: null,
              expireYear: null,
              url: null,
              koinUrl: null,
              tid: '1720447202',
              redemptionCode: null,
              giftCardId: null,
              giftCardProvider: null,
              giftCardAsDiscount: null,
              group: 'instantPayment',
              dueDate: null,
              paymentOrigin: null,
              accountId: null,
              parentAccountId: null,
              bankIssuedInvoiceIdentificationNumber: null,
              bankIssuedInvoiceIdentificationNumberFormatted: null,
              bankIssuedInvoiceBarCodeNumber: null,
              bankIssuedInvoiceBarCodeType: null,
              billingAddress: null,
            },
          ],
          sharedTransaction: false,
        },
      ],
    },
    clientPreferencesData: {
      locale: 'pt-BR',
      optinNewsLetter: false,
      savePersonalData: false,
      savePaymentData: false,
    },
    commercialConditionData: null,
    giftRegistryData: null,
    marketingData: {
      utmSource: null,
      utmPartner: null,
      utmMedium: null,
      utmCampaign: null,
      utmipage: null,
      utmiPart: null,
      utmiCampaign: null,
      coupon: null,
      marketingTags: [
        '',
      ],
    },
    storePreferencesData: {
      countryCode: 'BRA',
      timeZone: 'E. South America Standard Time',
      currencyCode: 'BRL',
      currencyLocale: 1046,
      currencySymbol: 'R$',
      currencyFormatInfo: {
        currencyDecimalDigits: 2,
        currencyDecimalSeparator: ',',
        currencyGroupSeparator: '.',
        currencyGroupSize: 3,
        startsWithCurrencySymbol: true,
      },
    },
    openTextField: null,
    invoiceData: {
      address: null,
      settleInvoices: [
        '002015518',
      ],
    },
    itemMetadata: {
      items: [
        {
          id: '355174',
          seller: '1',
          name: 'CAMISETA ESTAMPADA CYBER MARINHO - G',
          skuName: 'MARINHO - G',
          productId: '35462',
          refId: '006257731203',
          ean: '0062577312',
          imageUrl: 'http://lojausereserva.vteximg.com.br/arquivos/ids/6684702-55-55/0062577312_01.jpg?v=637828641798830000',
          detailUrl: '/camiseta-estampada-cyber0062577/p',
          assemblyOptions: [],
        },
      ],
    },
    taxData: null,
    customData: null,
    hooksData: null,
    changeData: null,
    subscriptionData: null,
    merchantContextData: null,
    salesChannel: '4',
    followUpEmail: 'ef562ffef5a74184be9e0865ea965dcb@ct.vtex.com.br',
    creationDate: '2023-08-22T15:18:57.9784287Z',
    lastChange: '2023-08-22T18:47:23.8506004Z',
    timeZoneCreationDate: '2023-08-22T12:18:57.9784287',
    timeZoneLastChange: '2023-08-22T15:47:23.8506004',
    isCompleted: true,
    hostName: 'applojausereservaqa',
    merchantName: null,
    userType: '',
    roundingError: 0,
    allowEdition: false,
    allowCancellation: false,
    isUserDataVisible: true,
    allowChangeSeller: false,
    orderFormCreationDate: '2023-08-22T14:29:33.5379042Z',
  },
];
