var item = {
  paymentType: "creditCard" | "pix" | "boleto" | "giftcard",
  paymentInfo: {
    creditCard: {
      id: "card_jWNRQjluwyt4Mr4Y",
      last_four_digits: "7152",
      holder_name: "artur as",
      exp_month: 8,
      exp_year: 2020,
    },
  },
  profile: {
    id: "9230923482",
    firstName: "Danilo",
    lastName: "Machado de Sousa",
    email: "danilo.sousa@globalsys.com.br",
    receiveEmail: "yes",
    gender: "male",
    fullName: "Danilo Machado de Sousa",
    rsvCPF: "74634434008",
    rsvBirthDate: "1953-02-12T00:00:00.000Z",
    rsvPhoneNumber: "34524562456",
  },
  items: {
    sku: 238492384,
    quantity: 1,
    title: "CAMISETA LIBERDADE RETÂNGULO",
    description:
      "Camiseta masculina Reserva. Perfeita para ficar confortável e garantir praticidade no seu dia a dia. Aposte na pedida certa! Manga curta ou manga longa, estampada ou lisa.",
    size: "P",
    color: "#F1F1F1",
    imagesUrls: [
      "https://www.usereserva.com/ccstore/v1/images/?source=/file/v8904640285793340471/products/0020878014_01.jpg&height=300&width=300",
    ],
  },
  shippingMethod: {
    id: 34738477,
    name: "Entrega padrão",
    value: 30.25,
  },
  shippingAddress: {
    country: "BR",
    lastName: null,
    address3: "Cobilandia",
    city: "Vix",
    address2: "243|Casa",
    prefix: null,
    address1: "Rua Itinga 90",
    postalCode: "29111-191",
    jobTitle: "",
    companyName: null,
    county: null,
    suffix: null,
    firstName: "",
    externalAddressId: null,
    phoneNumber: "",
    repositoryId: "16818875",
    faxNumber: null,
    middleName: null,
    state: "ES",
    id: "16818875",
  },
};
