export const images = {
  topBannerMock1: require('./img/topBannerMock1.png'),
  homeMock1: require('./img/homeMock1.png'),
  homeMock2: require('./img/homeMock2.png'),
  homeMock3: require('./img/homeMock3.png'),
  homeMock4: require('./img/homeMock4.png'),
  bannerOffer: require('./img/bannerOffer.png'),
  bannerCatalog: require('./img/bannerCatalog.png'),
  shirt1: require('./img/shirt1.png'),
  shirt2: require('./img/shirt2.png'),
  shirt3: require('./img/shirt3.png'),
  shirt4: require('./img/shirt4.png'),
  visa: require('./img/visa.png'),
  mastercard: require('./img/mastercard.png'),
  americanExpress: require('./img/americanExpress.png'),
  elo: require('./img/elo.png'),

  cardFront: require('./img/cardFront.png'),
  cardVerso: require('./img/cardVerso.png'),

  modalLivro: require('./img/modal-livro.png'),

  helpSizeGuide1: require('./img/help-size-guide1.png'),
  helpSizeGuide2: require('./img/help-size-guide2.png'),
  helpSizeGuide3: require('./img/help-size-guide3.png'),
  helpSizeGuide4: require('./img/help-size-guide4.png'),
  helpSizeGuide5: require('./img/help-size-guide5.png'),
  helpSizeGuide6: require('./img/help-size-guide6.png'),
  helpSizeGuide7: require('./img/help-size-guide7.png'),
  helpSizeGuide8: require('./img/help-size-guide8.png'),
  clothingCare1: require('./img/clothing-care1.png'),
  clothingCareWash: require('./img/clothingCareWash.png'),
  clothingCareBleach: require('./img/clothingCareBleach.png'),
  clothingCareDrying: require('./img/clothingCareDrying.png'),
  clothingCarePass: require('./img/clothingCarePass.png'),
  clothingCareProfessionalWashing: require('./img/clothingCareProfessionalWashing.png'),
  localReserva: require('./img/local-reserva.png'),
  pinYou: require('./img/pinYou.png'),
  bannerLogin: require('./img/banner-login.png'),
  headerLogin: require('./img/headerLogin.png'),
  purchaseConfirmation: require('./img/purchaseConfirmation.png'),
  withoutInternet: require('./img/withoutInternet.png'),
  update: require('./img/update.png'),
  searchNotFound: require('./img/searchNotFound.png'),
  saleOff: require('./img/saleOff.png'),
  logoQRCode: require('./img/logoQRCode.png'),
};

export const animations = {
  splash: require('./animations/splash.json'),
  bag: require('./animations/bag.json'),
  confirmation: require('./animations/confirmation.json'),
};
