export const images = {
  topBannerMock1: require('./img/topBannerMock1.png'),
  homeMock1: require('./img/homeMock1.png'),
  homeMock2: require('./img/homeMock2.png'),
  homeMock3: require('./img/homeMock3.png'),
  homeMock4: require('./img/homeMock4.png'),
  bannerOffer: require('./img/bannerOffer.png'),
  bannerCatalog: require('./img/bannerCatalog.png'),
  shirt1: require('./img/shirt1.png'),
  shirt2: require('./img/shirt2.png'),
  shirt3: require('./img/shirt3.png'),
  shirt4: require('./img/shirt4.png'),
  visa: require('./img/visa.png'),
  mastercard: require('./img/mastercard.png'),
  americanExpress: require('./img/americanExpress.png'),
  elo: require('./img/elo.png'),
  cardImage: require('./img/cardImage.png'),
};
