export const mockCurrentOrderForm = {
  orderFormId: '85b805c4c8c04d99b9cc0bf61d1c58e1',
  salesChannel: '4',
  loggedIn: false,
  isCheckedIn: false,
  storeId: null,
  checkedInPickupPointId: null,
  allowManualPrice: false,
  canEditData: true,
  userProfileId: null,
  userType: null,
  ignoreProfileData: false,
  value: 19929,
  messages: [],
  items: [
    {
      uniqueId: '52D9B57139FA4292909748AE8ED11774',
      id: '90368',
      productId: '3239',
      productRefId: '0054128',
      refId: '005412801401',
      ean: '0054128014',
      name: 'CAMISA ML SAMOA BRANCO - P',
      skuName: 'BRANCO - P',
      modalType: null,
      parentItemIndex: null,
      parentAssemblyBinding: null,
      assemblies: [],
      priceValidUntil: '2024-04-27T14:17:26Z',
      tax: 0,
      price: 27900,
      listPrice: 39900,
      manualPrice: null,
      manualPriceAppliedBy: null,
      sellingPrice: 19929,
      rewardValue: 0,
      isGift: false,
      additionalInfo: {
        dimension: null,
        brandName: 'RESERVA',
        brandId: '1',
        offeringInfo: null,
        offeringType: null,
        offeringTypeId: null,
      },
      preSaleDate: null,
      productCategoryIds: '/1/5/60/',
      productCategories: {
        1: 'Reserva',
        5: 'Masculino',
        60: 'camisas',
      },
      quantity: 1,
      seller: '1',
      sellerChain: [
        '1',
      ],
      imageUrl: 'http://lojausereserva.vteximg.com.br/arquivos/ids/6413946-55-55/0054128014_01.jpg?v=637692018478770000',
      detailUrl: '/camisa-ml-samoa0054128/p',
      components: [],
      bundleItems: [],
      attachments: [],
      attachmentOfferings: [],
      offerings: [
        {
          type: 'Embalagem pra Presente',
          id: '90310',
          name: 'Embalagem pra Presente',
          allowGiftMessage: true,
          attachmentOfferings: [
            {
              name: 'message',
              required: false,
              schema: {
                text: {
                  maximumNumberOfCharacters: 300,
                  domain: [],
                },
              },
            },
          ],
          price: 0,
        },
      ],
      priceTags: [
        {
          name: 'discount@price-f7c2175f-87a3-41fa-88c3-397b4ac987f3#a287b8e1-7b79-4ec4-86cf-f462598e10f6',
          value: -7971,
          rawValue: -79.71,
          isPercentual: false,
          identifier: 'f7c2175f-87a3-41fa-88c3-397b4ac987f3',
          owner: 'lojausereserva',
        },
      ],
      availability: 'available',
      measurementUnit: 'un',
      unitMultiplier: 1,
      manufacturerCode: null,
      priceDefinition: {
        calculatedSellingPrice: 19929,
        total: 19929,
        sellingPrices: [
          {
            value: 19929,
            quantity: 1,
          },
        ],
      },
    },
  ],
  packageItems: [
    {
      items: [
        {
          uniqueId: '52D9B57139FA4292909748AE8ED11774',
          id: '90368',
          productId: '3239',
          productRefId: '0054128',
          refId: '005412801401',
          ean: '0054128014',
          name: 'CAMISA ML SAMOA BRANCO - P',
          skuName: 'BRANCO - P',
          modalType: null,
          parentItemIndex: null,
          parentAssemblyBinding: null,
          assemblies: [],
          priceValidUntil: '2024-04-27T14:17:26Z',
          tax: 0,
          price: 27900,
          listPrice: 39900,
          manualPrice: null,
          manualPriceAppliedBy: null,
          sellingPrice: 19929,
          rewardValue: 0,
          isGift: false,
          additionalInfo: {
            dimension: null,
            brandName: 'RESERVA',
            brandId: '1',
            offeringInfo: null,
            offeringType: null,
            offeringTypeId: null,
          },
          preSaleDate: null,
          productCategoryIds: '/1/5/60/',
          productCategories: {
            1: 'Reserva',
            5: 'Masculino',
            60: 'camisas',
          },
          quantity: 1,
          seller: '1',
          sellerChain: [
            '1',
          ],
          imageUrl: 'http://lojausereserva.vteximg.com.br/arquivos/ids/6413946-55-55/0054128014_01.jpg?v=637692018478770000',
          detailUrl: '/camisa-ml-samoa0054128/p',
          components: [],
          bundleItems: [],
          attachments: [],
          attachmentOfferings: [],
          offerings: [
            {
              type: 'Embalagem pra Presente',
              id: '90310',
              name: 'Embalagem pra Presente',
              allowGiftMessage: true,
              attachmentOfferings: [
                {
                  name: 'message',
                  required: false,
                  schema: {
                    text: {
                      maximumNumberOfCharacters: 300,
                      domain: [],
                    },
                  },
                },
              ],
              price: 0,
            },
          ],
          priceTags: [
            {
              name: 'discount@price-f7c2175f-87a3-41fa-88c3-397b4ac987f3#a287b8e1-7b79-4ec4-86cf-f462598e10f6',
              value: -7971,
              rawValue: -79.71,
              isPercentual: false,
              identifier: 'f7c2175f-87a3-41fa-88c3-397b4ac987f3',
              owner: 'lojausereserva',
            },
          ],
          availability: 'available',
          measurementUnit: 'un',
          unitMultiplier: 1,
          manufacturerCode: null,
          priceDefinition: {
            calculatedSellingPrice: 19929,
            total: 19929,
            sellingPrices: [
              {
                value: 19929,
                quantity: 1,
              },
            ],
          },
        },
      ],
    }],
  selectableGifts: [],
  totalizers: [
    {
      id: 'Items',
      name: 'Total dos Itens',
      value: 27900,
    },
    {
      id: 'Discounts',
      name: 'Total dos Descontos',
      value: -7971,
    },
  ],
  shippingData: {
    address: null,
    logisticsInfo: [
      {
        itemIndex: 0,
        selectedSla: null,
        selectedDeliveryChannel: null,
        addressId: null,
        slas: [],
        shipsTo: [
          'BRA',
          'DEU',
          'SAL',
          'ARG',
          'AUS',
          'CAN',
          'CHL',
          'ECU',
          'ESP',
          'USA',
          'FRA',
          'IRL',
          'ITA',
          'MEX',
          'POL',
          'PRT',
          'GBR',
          'CHE',
          'SGP',
        ],
        itemId: '90368',
        deliveryChannels: [
          {
            id: 'delivery',
          },
          {
            id: 'pickup-in-point',
          },
        ],
      },
    ],
    selectedAddresses: [],
    availableAddresses: [],
    pickupPoints: [],
  },
  clientProfileData: null,
  paymentData: {
    updateStatus: 'updated',
    installmentOptions: [
      {
        paymentSystem: '1',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 19929,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 19929,
            total: 19929,
            sellerMerchantInstallments: [
              {
                id: 'LOJAUSERESERVA',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 19929,
                total: 19929,
              },
            ],
          },
          {
            count: 2,
            hasInterestRate: false,
            interestRate: 0,
            value: 9964,
            total: 19929,
            sellerMerchantInstallments: [
              {
                id: 'LOJAUSERESERVA',
                count: 2,
                hasInterestRate: false,
                interestRate: 0,
                value: 9964,
                total: 19929,
              },
            ],
          },
          {
            count: 3,
            hasInterestRate: false,
            interestRate: 0,
            value: 6643,
            total: 19929,
            sellerMerchantInstallments: [
              {
                id: 'LOJAUSERESERVA',
                count: 3,
                hasInterestRate: false,
                interestRate: 0,
                value: 6643,
                total: 19929,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '2',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 19929,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 19929,
            total: 19929,
            sellerMerchantInstallments: [
              {
                id: 'LOJAUSERESERVA',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 19929,
                total: 19929,
              },
            ],
          },
          {
            count: 2,
            hasInterestRate: false,
            interestRate: 0,
            value: 9964,
            total: 19929,
            sellerMerchantInstallments: [
              {
                id: 'LOJAUSERESERVA',
                count: 2,
                hasInterestRate: false,
                interestRate: 0,
                value: 9964,
                total: 19929,
              },
            ],
          },
          {
            count: 3,
            hasInterestRate: false,
            interestRate: 0,
            value: 6643,
            total: 19929,
            sellerMerchantInstallments: [
              {
                id: 'LOJAUSERESERVA',
                count: 3,
                hasInterestRate: false,
                interestRate: 0,
                value: 6643,
                total: 19929,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '3',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 19929,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 19929,
            total: 19929,
            sellerMerchantInstallments: [
              {
                id: 'LOJAUSERESERVA',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 19929,
                total: 19929,
              },
            ],
          },
          {
            count: 2,
            hasInterestRate: false,
            interestRate: 0,
            value: 9964,
            total: 19929,
            sellerMerchantInstallments: [
              {
                id: 'LOJAUSERESERVA',
                count: 2,
                hasInterestRate: false,
                interestRate: 0,
                value: 9964,
                total: 19929,
              },
            ],
          },
          {
            count: 3,
            hasInterestRate: false,
            interestRate: 0,
            value: 6643,
            total: 19929,
            sellerMerchantInstallments: [
              {
                id: 'LOJAUSERESERVA',
                count: 3,
                hasInterestRate: false,
                interestRate: 0,
                value: 6643,
                total: 19929,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '4',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 19929,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 19929,
            total: 19929,
            sellerMerchantInstallments: [
              {
                id: 'LOJAUSERESERVA',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 19929,
                total: 19929,
              },
            ],
          },
          {
            count: 2,
            hasInterestRate: false,
            interestRate: 0,
            value: 9964,
            total: 19929,
            sellerMerchantInstallments: [
              {
                id: 'LOJAUSERESERVA',
                count: 2,
                hasInterestRate: false,
                interestRate: 0,
                value: 9964,
                total: 19929,
              },
            ],
          },
          {
            count: 3,
            hasInterestRate: false,
            interestRate: 0,
            value: 6643,
            total: 19929,
            sellerMerchantInstallments: [
              {
                id: 'LOJAUSERESERVA',
                count: 3,
                hasInterestRate: false,
                interestRate: 0,
                value: 6643,
                total: 19929,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '9',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 19929,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 19929,
            total: 19929,
            sellerMerchantInstallments: [
              {
                id: 'LOJAUSERESERVA',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 19929,
                total: 19929,
              },
            ],
          },
          {
            count: 2,
            hasInterestRate: false,
            interestRate: 0,
            value: 9964,
            total: 19929,
            sellerMerchantInstallments: [
              {
                id: 'LOJAUSERESERVA',
                count: 2,
                hasInterestRate: false,
                interestRate: 0,
                value: 9964,
                total: 19929,
              },
            ],
          },
          {
            count: 3,
            hasInterestRate: false,
            interestRate: 0,
            value: 6643,
            total: 19929,
            sellerMerchantInstallments: [
              {
                id: 'LOJAUSERESERVA',
                count: 3,
                hasInterestRate: false,
                interestRate: 0,
                value: 6643,
                total: 19929,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '16',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 19929,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 19929,
            total: 19929,
            sellerMerchantInstallments: [
              {
                id: 'LOJAUSERESERVA',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 19929,
                total: 19929,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '72',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 19929,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 19929,
            total: 19929,
            sellerMerchantInstallments: [
              {
                id: 'LOJAUSERESERVA',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 19929,
                total: 19929,
              },
            ],
          },
          {
            count: 2,
            hasInterestRate: false,
            interestRate: 0,
            value: 9964,
            total: 19929,
            sellerMerchantInstallments: [
              {
                id: 'LOJAUSERESERVA',
                count: 2,
                hasInterestRate: false,
                interestRate: 0,
                value: 9964,
                total: 19929,
              },
            ],
          },
          {
            count: 3,
            hasInterestRate: false,
            interestRate: 0,
            value: 6643,
            total: 19929,
            sellerMerchantInstallments: [
              {
                id: 'LOJAUSERESERVA',
                count: 3,
                hasInterestRate: false,
                interestRate: 0,
                value: 6643,
                total: 19929,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '125',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 19929,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 19929,
            total: 19929,
            sellerMerchantInstallments: [
              {
                id: 'LOJAUSERESERVA',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 19929,
                total: 19929,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '172',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 19929,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 19929,
            total: 19929,
            sellerMerchantInstallments: [
              {
                id: 'LOJAUSERESERVA',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 19929,
                total: 19929,
              },
            ],
          },
        ],
      },
      {
        paymentSystem: '178',
        bin: null,
        paymentName: null,
        paymentGroupName: null,
        value: 19929,
        installments: [
          {
            count: 1,
            hasInterestRate: false,
            interestRate: 0,
            value: 19929,
            total: 19929,
            sellerMerchantInstallments: [
              {
                id: 'LOJAUSERESERVA',
                count: 1,
                hasInterestRate: false,
                interestRate: 0,
                value: 19929,
                total: 19929,
              },
            ],
          },
        ],
      },
    ],
    paymentSystems: [
      {
        id: 4,
        name: 'Mastercard',
        groupName: 'creditCardPaymentGroup',
        validator: {
          regex: '^((5(([1-2]|[4-5])[0-9]{8}|0((1|6)([0-9]{7}))|3(0(4((0|[2-9])[0-9]{5})|([0-3]|[5-9])[0-9]{6})|[1-9][0-9]{7})))|((508116)\\d{4,10})|((502121)\\d{4,10})|((589916)\\d{4,10})|(2[0-9]{15})|(67[0-9]{14})|(506387)\\d{4,10})',
          mask: '9999 9999 9999 9999',
          cardCodeRegex: '^[0-9]{3}$',
          cardCodeMask: '999',
          weights: [
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
          ],
          useCvv: true,
          useExpirationDate: true,
          useCardHolderName: true,
          useBillingAddress: true,
        },
        stringId: '4',
        template: 'creditCardPaymentGroup-template',
        requiresDocument: true,
        displayDocument: true,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2023-05-04T13:57:42.4674657Z',
        availablePayments: null,
      },
      {
        id: 2,
        name: 'Visa',
        groupName: 'creditCardPaymentGroup',
        validator: {
          regex: '^4[0-9]{15}$',
          mask: '9999 9999 9999 9999',
          cardCodeRegex: '^[0-9]{3}$',
          cardCodeMask: '999',
          weights: [
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
          ],
          useCvv: true,
          useExpirationDate: true,
          useCardHolderName: true,
          useBillingAddress: true,
        },
        stringId: '2',
        template: 'creditCardPaymentGroup-template',
        requiresDocument: true,
        displayDocument: true,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2023-05-04T13:57:42.4674657Z',
        availablePayments: null,
      },
      {
        id: 3,
        name: 'Diners',
        groupName: 'creditCardPaymentGroup',
        validator: {
          regex: '^3(0[0-5]|[68][0-9])[0-9]{11}$',
          mask: '9999 999999 9999',
          cardCodeRegex: '^[0-9]{3}$',
          cardCodeMask: '999',
          weights: [
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
          ],
          useCvv: true,
          useExpirationDate: true,
          useCardHolderName: true,
          useBillingAddress: true,
        },
        stringId: '3',
        template: 'creditCardPaymentGroup-template',
        requiresDocument: true,
        displayDocument: true,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2023-05-04T13:57:42.4674657Z',
        availablePayments: null,
      },
      {
        id: 9,
        name: 'Elo',
        groupName: 'creditCardPaymentGroup',
        validator: {
          regex: '^(50(67(0[78]|1[5789]|2[012456789]|3[01234569]|4[0-7]|53|7[4-8])|9(0(0[0-9]|1[34]|2[0-7]|3[0359]|4[01235678]|5[01235789]|6[0-9]|7[01346789]|8[01234789]|9[123479])|1(0[34568]|4[6-9]|5[1-8]|8[356789])|2(2[0-2]|5[78]|6[1-9]|7[0-9]|8[01235678]|90)|357|4(0[7-9]|1[0-9]|2[0-2]|31|5[7-9]|6[0-6]|84)|55[01]|636|7(2[2-9]|6[5-9])))|4(0117[89]|3(1274|8935)|5(1416|7(393|63[12])))|6(27780|36368|5(0(0(3[12356789]|4[0-7]|7[78])|4(0[6-9]|1[0234]|2[2-9]|3[045789]|8[5-9]|9[0-9])|5(0[012346789]|1[0-9]|2[0-9]|3[0178]|5[2-9]|6[0-6]|7[7-9]|8[0-8]|9[1-8])|72[0-7]|9(0[1-9]|1[0-9]|2[0128]|3[89]|4[6-9]|5[0145]|6[235678]|71))|16(5[2-9]|6[0-9]|7[01456789])|50(0[0-9]|1[02345678]|36|5[1267]))))\\d{0,13}$',
          mask: '9999 9999 9999 9999',
          cardCodeRegex: '^[0-9]{3}$',
          cardCodeMask: '999',
          weights: [
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
          ],
          useCvv: true,
          useExpirationDate: true,
          useCardHolderName: true,
          useBillingAddress: true,
        },
        stringId: '9',
        template: 'creditCardPaymentGroup-template',
        requiresDocument: true,
        displayDocument: true,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2023-05-04T13:57:42.4674657Z',
        availablePayments: null,
      },
      {
        id: 1,
        name: 'American Express',
        groupName: 'creditCardPaymentGroup',
        validator: {
          regex: '^3[47][0-9]{13}$',
          mask: '9999 999999 99999',
          cardCodeRegex: '^[0-9]{4}$',
          cardCodeMask: '9999',
          weights: [
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
            2,
            1,
          ],
          useCvv: true,
          useExpirationDate: true,
          useCardHolderName: true,
          useBillingAddress: true,
        },
        stringId: '1',
        template: 'creditCardPaymentGroup-template',
        requiresDocument: true,
        displayDocument: true,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2023-05-04T13:57:42.4674657Z',
        availablePayments: null,
      },
      {
        id: 125,
        name: 'Pix',
        groupName: 'instantPaymentPaymentGroup',
        validator: {
          regex: null,
          mask: null,
          cardCodeRegex: null,
          cardCodeMask: null,
          weights: null,
          useCvv: false,
          useExpirationDate: false,
          useCardHolderName: false,
          useBillingAddress: false,
        },
        stringId: '125',
        template: 'instantPaymentPaymentGroup-template',
        requiresDocument: false,
        displayDocument: false,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2023-05-04T13:57:42.4674657Z',
        availablePayments: null,
      },
      {
        id: 16,
        name: 'Vale',
        groupName: 'giftCardPaymentGroup',
        validator: {
          regex: null,
          mask: null,
          cardCodeRegex: null,
          cardCodeMask: null,
          weights: null,
          useCvv: false,
          useExpirationDate: false,
          useCardHolderName: false,
          useBillingAddress: false,
        },
        stringId: '16',
        template: 'giftCardPaymentGroup-template',
        requiresDocument: false,
        displayDocument: false,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2023-05-04T13:57:42.4674657Z',
        availablePayments: null,
      },
      {
        id: 72,
        name: 'PicPay',
        groupName: 'picPayPaymentGroup',
        validator: {
          regex: null,
          mask: null,
          cardCodeRegex: null,
          cardCodeMask: null,
          weights: null,
          useCvv: false,
          useExpirationDate: false,
          useCardHolderName: false,
          useBillingAddress: false,
        },
        stringId: '72',
        template: 'picPayPaymentGroup-template',
        requiresDocument: false,
        displayDocument: false,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2023-05-04T13:57:42.4674657Z',
        availablePayments: null,
      },
      {
        id: 172,
        name: 'Pagaleve',
        groupName: 'PagalevePaymentGroup',
        validator: {
          regex: null,
          mask: null,
          cardCodeRegex: null,
          cardCodeMask: null,
          weights: null,
          useCvv: false,
          useExpirationDate: false,
          useCardHolderName: false,
          useBillingAddress: false,
        },
        stringId: '172',
        template: 'PagalevePaymentGroup-template',
        requiresDocument: false,
        displayDocument: false,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2023-05-04T13:57:42.4674657Z',
        availablePayments: null,
      },
      {
        id: 178,
        name: 'Nubank',
        groupName: 'NubankPaymentGroup',
        validator: {
          regex: null,
          mask: null,
          cardCodeRegex: null,
          cardCodeMask: null,
          weights: null,
          useCvv: false,
          useExpirationDate: false,
          useCardHolderName: false,
          useBillingAddress: false,
        },
        stringId: '178',
        template: 'NubankPaymentGroup-template',
        requiresDocument: true,
        displayDocument: true,
        isCustom: false,
        description: null,
        requiresAuthentication: false,
        dueDate: '2023-05-04T13:57:42.4674657Z',
        availablePayments: null,
      },
    ],
    payments: [],
    giftCards: [],
    giftCardMessages: [],
    availableAccounts: [],
    availableTokens: [],
    availableAssociations: {},
  },
  marketingData: null,
  sellers: [
    {
      id: '1',
      name: 'Reserva',
      logo: '',
    },
  ],
  clientPreferencesData: {
    locale: 'pt-BR',
    optinNewsLetter: null,
  },
  commercialConditionData: null,
  storePreferencesData: {
    countryCode: 'BRA',
    saveUserData: true,
    timeZone: 'E. South America Standard Time',
    currencyCode: 'BRL',
    currencyLocale: 1046,
    currencySymbol: 'R$',
    currencyFormatInfo: {
      currencyDecimalDigits: 2,
      currencyDecimalSeparator: ',',
      currencyGroupSeparator: '.',
      currencyGroupSize: 3,
      startsWithCurrencySymbol: true,
    },
  },
  giftRegistryData: null,
  openTextField: null,
  invoiceData: null,
  customData: null,
  itemMetadata: {
    items: [
      {
        id: '90368',
        seller: '1',
        name: 'CAMISA ML SAMOA BRANCO - P',
        skuName: 'BRANCO - P',
        productId: '3239',
        refId: '005412801401',
        ean: '0054128014',
        imageUrl: 'http://lojausereserva.vteximg.com.br/arquivos/ids/6413946-55-55/0054128014_01.jpg?v=637692018478770000',
        detailUrl: '/camisa-ml-samoa0054128/p',
        assemblyOptions: [],
      },
    ],
  },
  hooksData: null,
  ratesAndBenefitsData: {
    rateAndBenefitsIdentifiers: [
      {
        id: 'f7c2175f-87a3-41fa-88c3-397b4ac987f3',
        name: 'Reserva | Exclusivo Ofertas',
        featured: false,
        description: '30% para 50%',
        matchedParameters: {
          'Seller@CatalogSystem': 'lojausereservaondemand,lojausereservago,1|inclusive',
          'productCluster@CatalogSystem': '2229|inclusive',
        },
        additionalInfo: null,
      },
    ],
    teaser: [],
  },
  subscriptionData: null,
  merchantContextData: null,
  itemsOrdination: null,
} as any;
