# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Push a new beta build to TestFlight"

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do |options|
    
    gradle(
      task: "clean bundleRelease"
      properties: {
        "android.injected.version.code" => 2023000123, #[increment + 1] app/src/build.grade.defaultConfig.versionCode
        "android.injected.version.name" => "2.1.10", #CI[tag]
      }
      )
    upload_to_play_store(
      json_key: options[:api_key_path],
    )
  end
end
