default_platform(:android)

platform :android do
  desc "Running tests on Android"
  lane :test do
    yarn(
      command: "",
      package_path: "../package.json"
    )

    yarn(
      command: "test",
      package_path: "../package.json"
    )
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    version_type = "patch"
    version_name = get_version_name(gradle_file_path: "app/build.gradle", ext_constant_name: "versionName")

    increment_version_name(
      gradle_file_path: "app/build.gradle",
      bump_type: version_type
    )

    increment_version_code(gradle_file_path: "app/build.gradle")

    gradle(
      task: "assemble",
      build_type: "Release",
      project_dir: "./",
    )

    slack(
      message: "Release Criada com sucesso",
      channel: "#build-fastlane",
      success: true,
      payload: {
        "Build Date" => Time.new.to_s,
        "Built by" => "Jenkins",
      },
      default_payloads: [:git_branch, :git_author],
      attachment_properties: {
        thumb_url: "https://fastlane.tools/assets/img/fastlane_icon.png",
        fields: [{
          title: "Versão",
          value: version_name,
          short: true
        }]
      },
      slack_url: "https://hooks.slack.com/services/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"
    )
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
